Ensure status is a string
If a CDX entry has a status that is an integer instead of a string
(which is what ArchiveWeb.page currently generates) will blow up:

```
Traceback (most recent call last):
  File "/Users/edsummers/Projects/pywb/pywb/warcserver/basewarcserver.py", line 77, in __call__
    result = endpoint(environ, **args)
  File "/Users/edsummers/Projects/pywb/pywb/warcserver/basewarcserver.py", line 46, in post_fullrequest
    return handler(params)
  File "/Users/edsummers/Projects/pywb/pywb/warcserver/handlers.py", line 160, in __call__
    out_headers, resp = loader(cdx, params)
  File "/Users/edsummers/Projects/pywb/pywb/warcserver/resource/responseloader.py", line 37, in __call__
    entry = self.load_resource(cdx, params)
  File "/Users/edsummers/Projects/pywb/pywb/warcserver/resource/responseloader.py", line 214, in load_resource
    if not status or not status.startswith(('2', '4', '5')):
AttributeError: 'int' object has no attribute 'startswith'
```

This commmit will guard against that by casting status values to a
string if they are an integer.